apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
      - name: hello
        image: {{ .Values.k8sJob.image.name }}:{{ .Values.k8sJob.image.tag }}
        imagePullPolicy: Never
      restartPolicy: OnFailure
